{- |
 - Module      :  02.hs
 - Author      :  Clement Poh
 -
 - Each new term in the Fibonacci sequence is generated by adding the previous
 - two terms. By starting with 1 and 2, the first 10 terms will be:
 -
 - 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 -
 - By considering the terms in the Fibonacci sequence whose values do not
 - exceed four million, find the sum of the even-valued terms.
 - -}
module Main where

fibs :: [Integer]
fibs = 1 : 2 : zipWith (+) fibs (tail fibs)

fibLimit :: [Integer]
fibLimit = takeWhile (< 4000000) fibs

fibEven :: [Integer]
fibEven = [x | x <- fibLimit, mod x 2 == 0]
