
{- |
 - Module      :  12.hs
 - Author      :  Clement Poh
 -
 - The sequence of triangle numbers is generated by adding the natural numbers.
 - So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
 - first ten terms would be:
 -
 - 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 -
 - Let us list the factors of the first seven triangle numbers:
 -
 -  1:  1
 -  3:  1,3
 -  6:  1,2,3,6
 -  10: 1,2,5,10
 -  15: 1,3,5,15
 -  21: 1,3,7,21
 -  28: 1,2,4,7,14,28
 -  We can see that 28 is the first triangle number to have over five divisors.
 -
 -  What is the value of the first triangle number to have over five hundred
 -  divisors?
 - -}
module Main where

intSquareRoot :: Integer -> Integer
intSquareRoot n = iSqRt 2 n where
    iSqRt a m
        | a * a > n = a - 1
        | otherwise = iSqRt (a + 1) m

factors :: Integer -> [(Integer, Integer)]
factors n = [(x, div n x) | x <- [1..intSquareRoot n], mod n x == 0]

triangles :: [Integer]
triangles = scanl (+) 1 [2..]

answer :: Integer
answer = head [x | x <- triangles, length (factors x) > 250]
